 # MTH8408 : Méthodes d'optimisation et contrôle optimal
 ## Laboratoire 1: Outils pour l'algèbre linéaire et l'optimisation
Tangi Migot

In [1]:
using Pkg; 
Pkg.activate("jump")

  Activating new project at `c:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump`

## JuMP: un langage de modélisation

### JuMP ?
JuMP est le language de modélisation pour l'optimisation natif dans Julia. En d'autres termes, on peut modéliser des problèmes d'optimisation en Julia grâce à ce package.

JuMP fait partie de l'organisation [jump-dev](https://jump.dev/) qui propose un ensemble d'outils concernant l'optimisation.

On pourra trouver beaucoup d'informations et d'exemples dans la documentation de JuMP [jump.dev/JuMP.jl/stable/](https://jump.dev/JuMP.jl/stable/)

### Installer JuMP
Comme on l'a fait pour `LinearAlgebra` il faut installer le package `JuMP` via le *package manager*.

In [3]:
Pkg.add("JuMP")

   Resolving package versions...

   Installed CodecBzip2 ───────── v0.8.1


   Installed BenchmarkTools ───── v1.4.0
   Installed Bzip2_jll ────────── v1.0.8+0


   Installed TranscodingStreams ─ v0.10.2


   Installed OrderedCollections ─ v1.6.3


   Installed MutableArithmetics ─ v1.4.0


   Installed DataStructures ───── v0.18.16


   Installed CodecZlib ────────── v0.7.3


   Installed JuMP ─────────────── v1.18.1


   Installed MathOptInterface ─── v1.25.0


    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Project.toml`
  [4076af6c] + JuMP v1.18.1
    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Manifest.toml`


  [6e4b80f9] + BenchmarkTools v1.4.0
  [523fee87] + CodecBzip2 v0.8.1
  [944b1d66] + CodecZlib v0.7.3
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.10.1
  [864edb3b] + DataStructures v0.18.16
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.15.1
  [ffbed154] + DocStringExtensions v0.9.3
  [f6369f11] + ForwardDiff v0.10.36
  [92d709cd] + IrrationalConstants v0.2.2
  [692b3bcd] + JLLWrappers v1.5.0
  [682c06a0] + JSON v0.21.4
  [4076af6c] + JuMP v1.18.1
  [2ab3a3ac] + LogExpFunctions v0.3.26
  [1914dd2f] + MacroTools v0.5.12
  [b8f27783] + MathOptInterface v1.25.0
  [d8a4904e] + MutableArithmetics v1.4.0
  [77ba4419] + NaNMath v1.0.2
  [bac558e1] + OrderedCollections v1.6.3
  [69de0a69] + Parsers v2.8.1
  [aea7be01] + PrecompileTools v1.2.0
  [21216c6a] + Preferences v1.4.1
  [276daf66] + SpecialFunctions v2.3.1
  [1e83bf80] + StaticArraysCore v1.4.2
  [3bb67fe8] + TranscodingStreams v0.10.2
  [6e34b625] + Bzip2_jll v1.0.8+0
  [efe28fd5] + OpenSpecFun_j

[83775a58] + Zlib_jll v1.2.13+1
  [8e850b90] + libblastrampoline_jll v5.8.0+1
  [8e850ede] + nghttp2_jll v1.52.0+1
  [3f19e933] + p7zip_jll v17.4.0+2


Precompiling 

project...


  ✓ OrderedCollections


  ✓ TranscodingStreams


  ✓ Bzip2_jll


  ✓ BenchmarkTools
  ✓ TranscodingStreams → TestExt


  ✓ DataStructures


  ✓ CodecZlib


  ✓ CodecBzip2


  ✓ MutableArithmetics


  ✓ MathOptInterface


  ✓ JuMP


  11 dependencies successfully precompiled in 323 seconds. 27 already precompiled.


Ensuite, on peut ajouter `JuMP` a notre environement et commencer à l'utiliser.

In [4]:
using JuMP

### Installer un solveur
Dans cet exemple, on va ajouter [`Ipopt`](https://en.wikipedia.org/wiki/IPOPT) qui est un package qui fournit un solveur pour l'optimisation nonlinéaire.

In [ ]:
] add Ipopt

In [5]:
#ou alors:
#using Pkg
Pkg.add("Ipopt")

   Resolving package versions...


   Installed MUMPS_seq_jll ── v500.600.200+0


   Installed SPRAL_jll ────── v2023.11.15+0


   Installed Hwloc_jll ────── v2.10.0+0
   Installed Ipopt_jll ────── v300.1400.1303+0
   Installed Ipopt ────────── v1.6.0
   Installed ASL_jll ──────── v0.1.3+0


   Installed METIS_jll ────── v5.1.2+0


   Installed OpenBLAS32_jll ─ v0.3.24+0


    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Project.toml`


  [b6b21f68] + Ipopt v1.6.0
    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Manifest.toml`


  [b6b21f68] + Ipopt v1.6.0
  [ae81ac8f] + ASL_jll v0.1.3+0
  [e33a78d0] + Hwloc_jll v2.10.0+0
  [9cc047cb] + Ipopt_jll v300.1400.1303+0
  [d00139f3] + METIS_jll v5.1.2+0
  [d7ed1dd3] + MUMPS_seq_jll v500.600.200+0
⌅ [656ef2d0] + OpenBLAS32_jll v0.3.24+0
  [319450e9] + SPRAL_jll v2023.11.15+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`

Precompiling project...


  ✓ ASL_jll


  ✓ Hwloc_jll
  ✓ OpenBLAS32_jll


  ✓ METIS_jll


  ✓ MUMPS_seq_jll


  ✓ SPRAL_jll


  ✓ Ipopt_jll


  ✓ Ipopt
  8 dependencies successfully precompiled in 59 seconds. 38 already precompiled.


In [8]:
Pkg.add("MathOptInterface")

   Resolving package versions...

    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Project.toml`
  [b8f27783] + MathOptInterface v1.25.0
  No Changes to `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\lab1\jump\Manifest.toml`


In [6]:
using Ipopt

In [ ]:
? ipopt

On installe aussi `MathOptInterface` qui permet de communiquer entre le modèle et le solveur.

In [11]:
using MathOptInterface

### Structure d'un modèle JuMP
Tous les modèles écrits avec JuMP ont la même structure:
- un objet `Model`, c'est l'initialisation de notre modèle.
- un objet `Optimizer`, qui spécifie un solveur.
- `Variables`, les variables du problème
- `Objective`, la fonction objectif
- `Constraints`, les contraintes.

#### Le modèle
Tous les problèmes modéliser avec JuMP sont des objets `Model`. Cet objet sera ensuite toujours mentionné lorsque l'on ajoutera des variables, la fonction objectif et des contraintes.

In [12]:
MonModel = Model()

A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

Il est également possible d'associer un solveur à ce modèle.

In [13]:
MonModel = Model(Ipopt.Optimizer) #utilise Ipopt comme solveur

A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: Ipopt

#### Les variables
Une première donnée importante de notre problème d'optimisation est la variable.

In [14]:
@variable(MonModel, 0 <= x <= 10)

x

In [15]:
unregister(MonModel, :x) # if you want to remove the variable x from the model

A ce stade, on peut aussi spécifier des contraintes de bornes sur les variables.

In [16]:
n = 10
l = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10]
u = [10; 11; 12; 13; 14; 15; 16; 17; 18; 19]
@variable(MonModel, l[i] <= x[i=1:n] <= u[i])

10-element Vector{VariableRef}:
 x[1]
 x[2]
 x[3]
 x[4]
 x[5]
 x[6]
 x[7]
 x[8]
 x[9]
 x[10]

ou plus simplement

In [17]:
@variable(MonModel, xx[i=1:n] >= 0)

10-element Vector{VariableRef}:
 xx[1]
 xx[2]
 xx[3]
 xx[4]
 xx[5]
 xx[6]
 xx[7]
 xx[8]
 xx[9]
 xx[10]

#### La fonction objectif
La fonction objectif se définit à l'aide de `@objective` et a trois arguments: le nom du modèle, le type d'optimisation (min ou max), et la fonction.

In [18]:
c = [2; 3; 4; 5] 
@objective(MonModel, Min, sum(c[i]*x[i] for i in 1:4))

2 x[1] + 3 x[2] + 4 x[3] + 5 x[4]

On peut aussi l'écrire sous forme de problème de maximisation.

In [19]:
@objective(MonModel, Max, sum(c[i]*x[i] for i in 1:4))

2 x[1] + 3 x[2] + 4 x[3] + 5 x[4]

Si la fonction objectif est nonlinéaire, on peut être plus précis et utiliser `@NLobjective`.

In [20]:
@NLobjective(MonModel, Min, exp(x[1]))

#### Les contraintes

In [21]:
TonModel = Model()
@variable(TonModel, x) #on peut avoir plusieurs types de variables
@variable(TonModel, y)
@constraint(TonModel, 5*x + 3*y <= 5) #une première contrainte

5 x + 3 y <= 5

Il peut être utile de nommer une contrainte pour s'y réferer ensuite.

In [22]:
@constraint(TonModel, un_nom_de_contrainte, 6*x + 4*y >= 5)

un_nom_de_contrainte : 6 x + 4 y >= 5

On peut aussi ajouter plusieurs contraints simultanément avec @constraints

In [23]:
@constraints(TonModel, begin
           2x <=  1
            x >= -1
       end)

(2 x <= 1, x >= -1)

In [24]:
TonModel[:un_nom_de_contrainte]

un_nom_de_contrainte : 6 x + 4 y >= 5

Si la contrainte est nonlinéaire, on peut être plus précis et utiliser `@NLconstraint`.

In [25]:
@NLconstraint(TonModel, x^2 == 0)

x ^ 2.0 - 0.0 == 0

On peut également introduire des contraintes plus génériques à l'aide de fonctions.

In [26]:
a = [1; -3; 5; 7] 
@variable(TonModel, w[1:4])
@constraint(TonModel, sum(a[i]*w[i] for i in 1:4) <= 3)

w[1] - 3 w[2] + 5 w[3] + 7 w[4] <= 3

On peut utiliser une boucle pour définir plusieurs contraintes.

In [27]:
@constraint(TonModel, conRef3[i in 1:3], 6*x + 4*y >= 5*i)
#= ou identiquement:
for i in 1:3
    @constraint(yourModel, 6*x + 4*y >= 5*i)
end
=#

3-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, ScalarShape}}:
 conRef3[1] : 6 x + 4 y >= 5
 conRef3[2] : 6 x + 4 y >= 10
 conRef3[3] : 6 x + 4 y >= 15

#### Exemple d'un code complet: Optimisation linéaire
On résout ici un problème d'optimisation linéaire
$$
\min_{x \in R^n} - x - 2y \ \text{sujet à} \ x + y \leq 1, 0 \leq x,y \leq 1.
$$

In [28]:
model = Model(Ipopt.Optimizer)

A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: Ipopt

On définit les variables.

In [29]:
@variable(model, 0 <= x <= 1)
@variable(model, 0 <= y <= 1)

y

La contrainte $x + y \leq 1$.

In [30]:
@constraint(model, x + y <= 1)

x + y <= 1

Enfin, on ajoute la fonction objectif.

In [31]:
@objective(model, Min, -x - 2y)

-x - 2 y

Pour résoudre ce problème, on peut utiliser la fonction `optimize`.

In [32]:
JuMP.optimize!(model)


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.13, running with linear solver MUMPS 5.6.2.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        2
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        2
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality c

Une fois la résolution terminée, on peut vérifier le status de la résolution.

In [33]:
@show JuMP.has_values(model)
@show JuMP.termination_status(model) == MathOptInterface.LOCALLY_SOLVED
@show JuMP.primal_status(model) == MathOptInterface.FEASIBLE_POINT
@show JuMP.dual_status(model) == MathOptInterface.FEASIBLE_POINT

JuMP.has_values(model) = true
JuMP.termination_status(model) == MathOptInterface.LOCALLY_SOLVED = true


JuMP.primal_status(model) == MathOptInterface.FEASIBLE_POINT = true
JuMP.dual_status(model) == MathOptInterface.FEASIBLE_POINT = true


true

On peut également faire une analyse sur la solution obtenue.

In [34]:
@show JuMP.value(x)              # Old syntax: getvalue(x)
@show JuMP.value(y)              # Old syntax: getvalue(y)
@show JuMP.objective_value(model)       # Old syntax: getobjectivevalue(model)

JuMP.value(x) = -4.860843938802289e-10
JuMP.value(y) = 1.0000000083700527


JuMP.objective_value(model) = -2.000000016254021


-2.000000016254021

#### Exemple d'un code complet: Optimisation nonlinéaire
$$
\min_{x,y} exp(x)+y \text{ s.à } exp(x) + sin(x) <= 0
$$

In [35]:
model = Model(Ipopt.Optimizer)
@variable(model, x)
@variable(model, y)

@NLobjective(model, Min, exp(x)+y)
@NLconstraint(model, exp(x)+sin(x) <=0)

(exp(x) + sin(x)) - 0.0 <= 0

In [36]:
optimize!(model)
println("x = ", value(x), " y = ", value(y))

This is Ipopt version 3.14.13, running with linear solver MUMPS 5.6.2.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        1
Number of nonzeros in Lagrangian Hessian.............:        2

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        1

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0000000e+00 1.00e+00 1.20e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00 

In [37]:
termination_status(model)

NORM_LIMIT::TerminationStatusCode = 17

In [38]:
vals = zeros(2)
x_index = JuMP.index(x)
y_index = JuMP.index(y)

MOI.VariableIndex(2)

In [39]:
d = NLPEvaluator(model)

Nonlinear.Evaluator with available features:
  * :Grad
  * :Jac
  * :JacVec
  * :Hess
  * :HessVec
  * :ExprGraph

In [40]:
MathOptInterface.initialize(d, [:Grad])

In [41]:
MathOptInterface.eval_objective(d, zeros(2))

1.0

In [42]:
∇f = zeros(2)
MathOptInterface.eval_objective_gradient(d, ∇f, zeros(2))
∇f

2-element Vector{Float64}:
 1.0
 1.0

In [43]:
J = zeros(1,2)
MathOptInterface.eval_constraint_jacobian(d, J, zeros(2))
J

1×2 Matrix{Float64}:
 2.0  0.0

#### Plus d'information
Dans ce cours, nous n'allons pas uniquement nous concentrer sur des problèmes linéaires, mais aussi nonlinéaire.
Vous trouverez plus d'informations pour ce cas dans la documentation de jump-dev:

[https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/introduction/](https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/introduction/)

et la documentation de MathOptInterface:

[https://jump.dev/MathOptInterface.jl/stable/](https://jump.dev/MathOptInterface.jl/stable/)

Et ça sera le sujet du projet !