 # MTH8408 : Méthodes d'optimisation et contrôle optimal
 ## Laboratoire 1: Outils pour l'algèbre linéaire et l'optimisation
Tangi Migot

## a) Gestion de l'environement de packages

Certaines des fonctionnalités de Julia sont encapsulées dans des **packages**. C'est le cas des fonctions pour l'algèbre linéaire qui sont dans `LinearAlgebra`.
Pour accèder à l'environement qui gère ces packages on utilise `]`.

Pour ajouter `LinearAlgebra`:

In [4]:
using Pkg

In [5]:
Pkg.add("LinearAlgebra")

    Updating registry at `C:\Users\jgpal\.julia\registries\General.toml`


   Resolving package versions...


    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\Project.toml`
  [37e2e46d] + LinearAlgebra
    Updating `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\Manifest.toml`
  [56f22d72] + Artifacts
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [e66e0078] + CompilerSupportLibraries_jll v1.0.5+1
  [4536629a] + OpenBLAS_jll v0.3.23+2
  [8e850b90] + libblastrampoline_jll v5.8.0+1

Une alternative est d'utiliser le package `Pkg` qui est installer d'office avec Julia.

In [ ]:
using Pkg #using permet d'utiliser les fonctionnalités d'un package.
Pkg.add("LinearAlgebra")

Pour l'utiliser dans notre environement, on utilise `using`.

In [6]:
using LinearAlgebra

Si vous ne savez plus quels packages sont installés ou vous souhaitez connaître la version des packages installés, on utilise `status`.

In [7]:
Pkg.status()

Status `C:\Users\jgpal\OneDrive\Documents\GitHub\MTH8408-Hiv24\Project.toml`
  [37e2e46d] LinearAlgebra


## b) Algèbre linéaire

### **i) Création des vecteurs**

In [8]:
v = [1; 2; 3]  # Vecteur de longueur 3
v = [1, 2, 3]  # Vecteur de longueur 3

3-element Vector{Int64}:
 1
 2
 3

In [9]:
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

Les tableaux (Array) ont un type particulier en Julia, il est paramétrique. On fait la différence entre un tableau de réels ou d'entiers.

### ii) Création des matrices

In [10]:
M = [1 2; 3 4]  # Matrice de taille 2 x 2
M = zeros(2, 2)  # Matrice contenant que des 0 de taille 2 x 2
M = ones(2, 2)  # Matrice contenant que des 1 de taille 2 x 2
M = I  # Matrice identité dont la dimension s'adapte aux opérations

UniformScaling{Bool}
true*I

In [11]:
v = [1, 2, 3]
M = Diagonal(v) #matrice avec v sur la diagonale
M = diagm(0 => v)
M = diagm(-1 => v)

4×4 Matrix{Int64}:
 0  0  0  0
 1  0  0  0
 0  2  0  0
 0  0  3  0

In [12]:
x = [1, 2, 3]
y = [4, 5, 6, 7]
z = [8, 9, 10]
N = Tridiagonal(x, y, z)  # Création d'une matrice tridiagonale

4×4 Tridiagonal{Int64, Vector{Int64}}:
 4  8  ⋅   ⋅
 1  5  9   ⋅
 ⋅  2  6  10
 ⋅  ⋅  3   7

In [13]:
M = [1 2; 3 4]
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

### iii) Manipulation des vecteurs et des matrices

In [14]:
transpose(M)  # Matrice transposéee Mᵀ
M'  # Matrice adjointe Mᴴ (transposée de la matrice conjuguée)

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [15]:
#M = hcat([1 2], [1 2]) # Concaténation horizontale
M = vcat([1 2], [1 2]) #  Concaténation verticale

2×2 Matrix{Int64}:
 1  2
 1  2

Accès aux composants d'un vecteur ou d'une matrice

In [16]:
M = [1 2; 3 4]
M[2, 2] # Accès au coefficient (2, 2) de M
M[1:2, 1]  # Accès aux lignes 1 à 2 de M
D = diag(M)  # Vecteur contenant la diagonale de la matrice M
nrow, ncol = size(M)  # Dimensions de la matrices M 

(2, 2)

In [17]:
#LowerTriangular(M)  # Triangle inférieur de M
#UpperTriangular(M)  # Triangle supérieur de M
tril(M)
#triu(M)
#UnitLowerTriangular(M)  # Triangle strictement inférieur de M avec diagonale unitaire
#UnitUpperTriangular(M)  # Triangle strictement supérieur de M avec diagonale unitaire

2×2 Matrix{Int64}:
 1  0
 3  4

### iv) Opérations mathématiques

In [18]:
A = ones(2,2)
B = [1 2; 3 4]
A * B  # Produit matriciel de A et B

2×2 Matrix{Float64}:
 4.0  6.0
 4.0  6.0

In [19]:
A .* B  # Produit des coefficients termes à termes

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [20]:
1 .+ A #ajoute 1 à toutes les composantes de A

2×2 Matrix{Float64}:
 2.0  2.0
 2.0  2.0

In [ ]:
inv(B)  # Inverse d'une matrice

In [ ]:
det(A)  # Déterminant d'une matrice

In [ ]:
tr(A)  # Trace d'une matrice

In [ ]:
val, vec = eigen(A)  # Valeurs propres et vecteurs propres de A
val

In [ ]:
b = B * ones(2)
x = B \ b  # Résolution du système linéaire Ax = b

In [ ]:
x = inv(B) * b